apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - resources

secretGenerator:
  - name: db-creds
    literals:
      - password=password1

patches:
  - path: patches/api.yaml
